# Generated by Django 5.0.1 on 2024-03-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_post_poste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste',
            old_name='password2',
            new_name='auther',
        ),
    ]
