# Generated by Django 5.0.1 on 2024-03-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_password2_poste_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
