# Generated by Django 5.0.1 on 2024-04-21 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_poste_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poste',
        ),
    ]
