# Generated by Django 5.0.1 on 2024-04-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_delete_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NameAuthor', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=1000)),
                ('NameStorey', models.CharField(max_length=5000)),
            ],
        ),
    ]
